// Clinical Clarity design tokens — ported from clinical_clarity/DESIGN.md
// and the tailwind-config blocks in the UI mockups.
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#006a63',
        'on-primary': '#ffffff',
        'primary-container': '#4db6ac',
        'on-primary-container': '#00433f',
        'primary-fixed': '#8ef4e9',
        'primary-fixed-dim': '#71d7cd',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        'inverse-primary': '#71d7cd',
        secondary: '#436556',
        'on-secondary': '#ffffff',
        'secondary-container': '#c2e8d5',
        'on-secondary-container': '#476a5a',
        'secondary-fixed': '#c5ebd8',
        'secondary-fixed-dim': '#a9cfbc',
        'on-secondary-fixed': '#002116',
        'on-secondary-fixed-variant': '#2b4d3f',
        tertiary: '#516161',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#98a9a8',
        'on-tertiary-container': '#2e3e3e',
        'tertiary-fixed': '#d4e6e5',
        'tertiary-fixed-dim': '#b8cac9',
        'on-tertiary-fixed': '#0e1e1e',
        'on-tertiary-fixed-variant': '#3a4a49',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f4faff',
        'surface-dim': '#cfdce4',
        'surface-bright': '#f4faff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#e9f6fd',
        'surface-container': '#e3f0f8',
        'surface-container-high': '#ddeaf2',
        'surface-container-highest': '#d7e4ec',
        'surface-variant': '#d7e4ec',
        'surface-tint': '#006a63',
        'on-surface': '#111d23',
        'on-surface-variant': '#3d4947',
        'inverse-surface': '#263238',
        'inverse-on-surface': '#e6f3fb',
        outline: '#6d7a77',
        'outline-variant': '#bdc9c6',
        background: '#f4faff',
        'on-background': '#111d23',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '24px',
        'section-gap': '48px',
        base: '8px',
        'card-padding': '20px',
        gutter: '16px',
      },
      fontFamily: {
        display: ['var(--font-geist-sans)', 'sans-serif'],
        'headline-lg': ['var(--font-geist-sans)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-geist-sans)', 'sans-serif'],
        'headline-md': ['var(--font-geist-sans)', 'sans-serif'],
        'label-md': ['var(--font-geist-sans)', 'sans-serif'],
        'label-sm': ['var(--font-geist-sans)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
